@startuml
'https://plantuml.com/class-diagram

class Section {
    - String name
    - List<Presentation> presentations
}

Section o-- Conference : "has"
Section --o "many" Presentation : has
@enduml
